import{LEVELS,TILE}from'./levels.js';
for(const b of document.querySelectorAll('[data-level]'))b.onclick=()=>start(Number(b.dataset.level));
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),overlay=document.querySelector('#overlay'),title=document.querySelector('#overlay-title'),copy=document.querySelector('#overlay-copy'),primary=document.querySelector('#primary');ctx.imageSmoothingEnabled=false;
const keys=new Set(),pressed=new Set();let state='title',levelIndex=0,level,player,camera=0,elapsed=0,deaths=0,pearls=0,shake=0,last=0,sound=true,tip='',tipTime=0,particles=[];const save=JSON.parse(localStorage.getItem('reelbound-save-v2')||'{"unlocked":1,"times":{}}');
class AudioFX{constructor(){this.ctx=null}tone(f,d=.08,v=.04,type='square'){if(!sound)return;this.ctx??=new AudioContext;const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,this.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,this.ctx.currentTime+d);o.connect(g).connect(this.ctx.destination);o.start();o.stop(this.ctx.currentTime+d)}}const fx=new AudioFX;
const down=(...c)=>c.some(k=>keys.has(k)),hit=(...c)=>c.some(k=>pressed.has(k)),rects=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
function runtime(){level._pearls=level.pearls.map((p,id)=>({x:p[0]*TILE+16,y:p[1]*TILE+16,taken:false,id}));level._enemies=level.enemies.map((p,id)=>({x:p[0]*TILE,y:p[1]*TILE,w:26,h:22,vx:id%2?52:-52,alive:true}));level._switches=level.switches.map(s=>({x:s[0]*TILE,y:s[1]*TILE,w:24,h:24,id:s[2],on:false}));level._movers=level.movers.map((m,id)=>({x:m[0]*TILE,y:m[1]*TILE,w:m[2]*TILE,h:m[3]*TILE,bx:m[0]*TILE,by:m[1]*TILE,dx:m[4],dy:m[5],speed:m[6],phase:id*.83,lastX:0,lastY:0}));for(const s of level.signs)s.seen=false}
function spawn(x,y){player={x,y,w:22,h:30,vx:0,vy:0,ground:false,coyote:0,jumpBuffer:0,dashes:1,dashTime:0,dashLock:0,hook:null,face:1,inv:0,wall:0,wallTime:0,waveTime:0,checkpoint:{x,y},trail:[]}}
function resetLevel(i=levelIndex){levelIndex=i;level=LEVELS[i];runtime();spawn(level.start[0]*TILE,level.start[1]*TILE);camera=elapsed=deaths=pearls=0;tip='';tipTime=0;particles=[]}
function start(i=0){resetLevel(i);state='play';overlay.classList.add('hidden');fx.tone(330,.12)}
function staticSolids(){const a=level.platforms.map(p=>({x:p[0]*TILE,y:p[1]*TILE,w:p[2]*TILE,h:p[3]*TILE,type:'ground'}));for(const g of level.gates)if(!level._switches.some(s=>s.id===g[4]&&s.on))a.push({x:g[0]*TILE,y:g[1]*TILE,w:g[2]*TILE,h:g[3]*TILE,type:'gate'});return a}
const allSolids=()=>[...staticSolids(),...level._movers.map(m=>({...m,type:'mover'}))];
function puff(x,y,c='#fff1cf',n=5){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*110,vy:-Math.random()*90-20,t:.35+Math.random()*.25,c})}
function die(){if(player.inv>0)return;const cp={...player.checkpoint};deaths++;shake=12;fx.tone(85,.3,.07,'sawtooth');puff(player.x+11,player.y+15,'#ef6a4c',10);spawn(cp.x,cp.y);player.checkpoint=cp;player.inv=1}
function moveAxis(axis,amount){player[axis]+=amount;let collided=0,landed=false;for(const r of allSolids())if(rects(player,r)){if(axis==='x'){player.x=amount>0?r.x-player.w:r.x+r.w;collided=amount>0?1:-1;player.vx=0}else{player.y=amount>0?r.y-player.h:r.y+r.h;collided=amount>0?1:-1;if(amount>0){landed=player.ground=true;player.dashes=1;if(r.type==='mover')player.x+=r.x-r.lastX}player.vy=0}}return{collided,landed}}
function nearestHook(){let best=null,dist=250;for(const h of level.hooks){const x=h[0]*TILE+16,y=h[1]*TILE+16,d=Math.hypot(x-player.x-11,y-player.y-8);if(d<dist&&y<player.y+90){best={x,y};dist=d}}return best}
function showTip(a,b){tip=`${a}: ${b}`;tipTime=4.5}
function movers(){for(const m of level._movers){m.lastX=m.x;m.lastY=m.y;const s=(Math.sin(elapsed*m.speed+m.phase)+1)/2;m.x=m.bx+m.dx*s;m.y=m.by+m.dy*s}}
function update(dt){if(state!=='play')return;elapsed+=dt;movers();player.inv=Math.max(0,player.inv-dt);player.coyote=player.ground?.11:Math.max(0,player.coyote-dt);player.jumpBuffer=Math.max(0,player.jumpBuffer-dt);player.wallTime=Math.max(0,player.wallTime-dt);player.waveTime=Math.max(0,player.waveTime-dt);player.dashLock=Math.max(0,player.dashLock-dt);tipTime=Math.max(0,tipTime-dt);
 const jumpHit=hit('Space','ArrowUp','KeyZ'),jumpHeld=down('Space','ArrowUp','KeyZ');if(jumpHit)player.jumpBuffer=.13;const ix=(down('KeyD','ArrowRight')?1:0)-(down('KeyA','ArrowLeft')?1:0),iy=(down('KeyS','ArrowDown')?1:0)-(down('KeyW','ArrowUp')?1:0);if(ix)player.face=ix;
 if(hit('KeyE','KeyX')&&!player.hook){player.hook=nearestHook();if(player.hook){fx.tone(520);puff(player.hook.x,player.hook.y,'#ffcf63',4)}}else if(hit('KeyE','KeyX')&&player.hook)player.hook=null;
 if(hit('ShiftLeft','ShiftRight','KeyC')&&player.dashes&&player.dashLock<=0){let dx=ix,dy=iy;if(!dx&&!dy)dx=player.face;const mag=Math.hypot(dx,dy)||1;player.dashes--;player.dashTime=.16;player.dashLock=.2;player.vx=dx/mag*500;player.vy=dy/mag*500;player.hook=null;fx.tone(190,.13);puff(player.x+11,player.y+16,'#78ddd1',7)}
 const canWall=player.wall&&player.wallTime>0&&!player.ground;if(player.jumpBuffer&&(player.coyote>0||canWall)){if(canWall){player.vx=-player.wall*335;player.vy=-410;player.face=-player.wall;fx.tone(560)}else{player.vy=-405;if(player.waveTime>0)player.vx*=1.08;fx.tone(player.waveTime>0?690:420)}player.jumpBuffer=player.coyote=0;player.ground=false;puff(player.x+11,player.y+28,'#d8efe3',5)}if(!jumpHeld&&player.vy<-170&&player.dashTime<=0)player.vy+=1150*dt;
 const accel=player.ground?1800:1050,friction=player.waveTime>0?.985:(player.ground?.80:.94),maxRun=player.waveTime>0?455:285;if(player.dashTime<=0){player.vx=(player.vx+ix*accel*dt)*Math.pow(friction,dt*10);player.vx=Math.max(-maxRun,Math.min(maxRun,player.vx));player.vy+=1050*dt}
 if(player.hook){const dx=player.hook.x-player.x-11,dy=player.hook.y-player.y-8,d=Math.hypot(dx,dy);player.vx+=dx/d*720*dt;player.vy+=dy/d*720*dt;if(d>255)player.hook=null;if(jumpHit){player.hook=null;player.vy=Math.min(player.vy,-330);player.vx+=player.face*90;fx.tone(620)}}
 for(const z of level.windZones)if(rects(player,{x:z[0]*TILE,y:z[1]*TILE,w:z[2]*TILE,h:z[3]*TILE})){player.vx+=z[4]*dt;player.vy+=z[5]*dt}if(level.wind)player.vx+=level.wind*dt;
 player.dashTime=Math.max(0,player.dashTime-dt);player.ground=false;const mx=moveAxis('x',player.vx*dt);player.wall=mx.collided;player.wallTime=mx.collided?.12:player.wallTime;if(player.wall&&player.vy>90&&((player.wall>0&&ix>0)||(player.wall<0&&ix<0)))player.vy=Math.min(player.vy,105);
 const beforeVy=player.vy,my=moveAxis('y',player.vy*dt);if(my.landed&&beforeVy>180&&player.dashTime>0&&iy>0&&ix){player.waveTime=.65;player.vx=ix*455;player.dashTime=0;shake=4;showTip('WAVEDASH','Jump now to carry your speed!');fx.tone(760,.1);puff(player.x+11,player.y+29,'#78ddd1',9)}
 for(const s of level.springs){const r={x:s[0]*TILE,y:s[1]*TILE+20,w:TILE,h:12};if(rects(player,r)&&player.vy>=0){player.y=r.y-player.h;player.vy=-600;player.dashes=1;fx.tone(820,.16);puff(player.x+11,r.y,'#f3cd59',8)}}for(const h of level.hazards)if(rects(player,{x:h[0]*TILE,y:h[1]*TILE,w:h[2]*TILE,h:h[3]*TILE}))die();if(player.y>560)die();
 for(const c of level.checkpoints)if(player.x>c[0]*TILE&&player.checkpoint.x<c[0]*TILE){player.checkpoint={x:c[0]*TILE,y:c[1]*TILE};showTip('CHECKPOINT','The lantern is lit');fx.tone(660,.22,.05,'triangle')}for(const s of level._switches)if(!s.on&&rects(player,s)){s.on=true;showTip('WINCH OPEN','A distant gate moved');fx.tone(300,.25,.06,'triangle')}for(const s of level.signs)if(Math.abs(player.x-s[0]*TILE)<42&&Math.abs(player.y-s[1]*TILE)<70&&!s.seen){s.seen=true;showTip(s[2],s[3])}
 const solids=staticSolids();for(const e of level._enemies){if(!e.alive)continue;e.x+=e.vx*dt;if(!solids.some(r=>rects({x:e.x,y:e.y+e.h+3,w:e.w,h:3},r)))e.vx*=-1;if(rects(player,e)){if(player.vy>100||player.dashTime>0){e.alive=false;player.vy=-235;player.dashes=1;fx.tone(120,.08);puff(e.x+13,e.y+10,'#ef6a4c',7)}else die()}}for(const p of level._pearls)if(!p.taken&&Math.hypot(player.x-p.x,player.y-p.y)<30){p.taken=true;pearls++;fx.tone(780,.12);puff(p.x,p.y,'#fff1cf',5)}
 if(rects(player,{x:level.goal[0]*TILE,y:level.goal[1]*TILE,w:40,h:64}))complete();camera+=(Math.max(0,Math.min(level.width*TILE-960,player.x-330))-camera)*Math.min(1,dt*5);player.trail.push({x:player.x,y:player.y,t:.16});if(player.trail.length>8)player.trail.shift();for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=260*dt;p.t-=dt}particles=particles.filter(p=>p.t>0);pressed.clear()}
const fmt=s=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
function complete(){state='complete';const score=Math.max(0,30000-Math.floor(elapsed*40)-deaths*500+pearls*350),rank=elapsed<level.par*.72?'S':elapsed<level.par?'A':elapsed<level.par*1.35?'B':'C';save.unlocked=Math.max(save.unlocked,levelIndex+2);save.times[levelIndex]=Math.min(save.times[levelIndex]||9999,elapsed);localStorage.setItem('reelbound-save-v2',JSON.stringify(save));title.textContent=`${level.fish} caught!`;copy.innerHTML=`${level.name} clear - ${fmt(elapsed)} - ${pearls}/${level.pearls.length} pearls - ${deaths} falls<br><strong>RANK ${rank} - ${score} PTS</strong>`;primary.textContent=levelIndex===LEVELS.length-1?'VIEW CATCH LOG':'NEXT VOYAGE';overlay.classList.remove('hidden');fx.tone(660,.35,.06,'triangle')}
function px(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x-camera),Math.round(y),w,h)}
function drawPlayer(){const x=player.x,y=player.y,bob=player.ground&&Math.abs(player.vx)>25?Math.sin(elapsed*20)*2:0;if(player.inv&&Math.floor(player.inv*10)%2)return;if(player.dashTime>0)for(const t of player.trail)px(t.x+4,t.y+5,15,22,`rgba(61,190,181,${Math.max(0,t.t*1.8)})`);if(player.hook){ctx.strokeStyle='#f4e1b8';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x+11-camera,y+8);ctx.quadraticCurveTo((x+player.hook.x)/2-camera,y+70,player.hook.x-camera,player.hook.y);ctx.stroke()}const flip=player.face<0;px(x+5,y+5+bob,14,12,'#e7a936');px(x+2,y+2+bob,19,6,'#f4c649');px(x+(flip?6:13),y+9+bob,3,3,'#397c85');px(x+7,y+12+bob,11,6,'#9a563b');px(x+3,y+17+bob,17,10,'#176c70');px(x+(flip?1:15),y+19+bob,6,4,'#d69a6b');px(x+4,y+27+bob,6,3,'#2d2930');px(x+14,y+27+bob,6,3,'#2d2930')}
function backdrop(){const g=ctx.createLinearGradient(0,0,0,540);g.addColorStop(0,level?.sky[0]||'#102d43');g.addColorStop(1,level?.sky[1]||'#da7656');ctx.fillStyle=g;ctx.fillRect(0,0,960,540);if(!level)return;for(let n=0;n<3;n++)for(let i=0;i<10;i++){const x=((i*227-camera*(.08+n*.08))%1400+1400)%1400,y=220+n*80+(i%3)*18;ctx.fillStyle=['#ffffff0b','#07172618','#07172632'][n];ctx.beginPath();ctx.moveTo(x-100,y+160);ctx.lineTo(x+50,y-(i%2)*45);ctx.lineTo(x+190,y+160);ctx.fill()}px(camera,486,960,54,level.water);for(let i=0;i<34;i++)px(camera+i*32+(elapsed*16)%32,486+Math.sin(i+elapsed*2)*4,17,3,'#b9f0df')}
function draw(){backdrop();if(!level)return;ctx.save();ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.82;for(const z of level.windZones)for(let i=0;i<8;i++)px(z[0]*TILE+((elapsed*80+i*67)%(z[2]*TILE)),z[1]*TILE+24+(i*53)%(z[3]*TILE),24,2,z[5]?'#72e2bd44':'#d9edf055');for(const p of level.platforms){const[x,y,w,h]=p;px(x*TILE,y*TILE,w*TILE,h*TILE,'#163946');px(x*TILE,y*TILE,w*TILE,6,level.accent);for(let i=0;i<w;i+=2)px((x+i)*TILE,y*TILE+13,18,5,'#0e2b37')}for(const m of level._movers){px(m.x,m.y,m.w,m.h,'#755544');px(m.x,m.y,m.w,6,'#e0b157')}for(const g of level.gates)if(!level._switches.some(s=>s.id===g[4]&&s.on)){px(g[0]*TILE,g[1]*TILE,g[2]*TILE,g[3]*TILE,'#a66f43')}
 for(const h of level.hazards)for(let i=0;i<h[2];i++){const x=(h[0]+i)*TILE,y=h[1]*TILE;px(x,y+20,32,12,'#0a405b');px(x+4,y+5,7,20,'#d9e9dd');px(x+18,y,7,25,'#d9e9dd')}for(const h of level.hooks){const x=h[0]*TILE+16,y=h[1]*TILE+16;px(x-5,y-5,10,10,'#ffbd47');px(x-2,y+5,4,7,'#fff1cf')}for(const s of level.springs){px(s[0]*TILE,s[1]*TILE+22,32,10,'#ef6a4c');px(s[0]*TILE+6,s[1]*TILE+17,20,5,'#ffcf63')}for(const c of level.checkpoints){const a=player.checkpoint.x>=c[0]*TILE;px(c[0]*TILE+12,c[1]*TILE-24,4,54,'#bf9462');px(c[0]*TILE+16,c[1]*TILE-22,18,14,a?'#72e2bd':'#526875')}for(const s of level._switches){px(s.x,s.y,s.w,s.h,s.on?'#72e2bd':'#d49b3d');px(s.x+6,s.y+5,12,5,'#fff1cf')}for(const s of level.signs){px(s[0]*TILE,s[1]*TILE,6,30,'#6f4e3c');px(s[0]*TILE-10,s[1]*TILE-7,30,17,'#b47b45')}
 for(const p of level._pearls)if(!p.taken){px(p.x-5,p.y-5,10,10,'#fff4d7');px(p.x-2,p.y-8,4,3,'#82e5d5')}for(const e of level._enemies)if(e.alive){px(e.x,e.y+7,26,15,'#e65e48');px(e.x+4,e.y+2,5,7,'#f2b950');px(e.x+17,e.y+2,5,7,'#f2b950');px(e.x+(e.vx>0?19:4),e.y+10,3,3,'#071726')}for(const p of particles)px(p.x,p.y,3,3,p.c);const gx=level.goal[0]*TILE,gy=level.goal[1]*TILE;px(gx+14,gy,4,66,'#e4c287');px(gx+18,gy+8,34,20,'#ef6a4c');px(gx+27,gy+14,12,5,'#fff1cf');drawPlayer();ctx.restore();ctx.fillStyle='#071726dd';ctx.fillRect(14,14,400,58);ctx.fillStyle='#fff1cf';ctx.font='bold 14px DM Mono';ctx.fillText(`${levelIndex+1}/${LEVELS.length}  ${level.name.toUpperCase()}`,27,37);ctx.fillStyle='#7fded2';ctx.font='11px DM Mono';ctx.fillText(`${fmt(elapsed)}  -  PEARLS ${pearls}/${level.pearls.length}  -  FALLS ${deaths}  -  DASH ${player.dashes?'READY':'EMPTY'}`,27,58);if(tipTime>0){ctx.fillStyle='#071726e8';ctx.fillRect(235,450,490,52);ctx.strokeStyle='#d6b56a';ctx.strokeRect(235,450,490,52);ctx.fillStyle='#fff1cf';ctx.textAlign='center';ctx.font='bold 12px DM Mono';ctx.fillText(tip,480,481);ctx.textAlign='left'}}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}
addEventListener('keydown',e=>{if(!keys.has(e.code))pressed.add(e.code);keys.add(e.code);if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'&&state==='play')pause();if(e.code==='KeyR'&&state==='play'){const cp={...player.checkpoint};spawn(cp.x,cp.y);player.checkpoint=cp}});addEventListener('keyup',e=>keys.delete(e.code));
function pause(){state='paused';title.textContent='Lines slackened';copy.textContent='The tide will wait for you.';primary.textContent='RESUME';overlay.classList.remove('hidden')}
for(const b of document.querySelectorAll('[data-key]')){const code=b.dataset.key,on=e=>{e.preventDefault();if(!keys.has(code))pressed.add(code);keys.add(code);b.classList.add('active')},off=e=>{e.preventDefault();keys.delete(code);b.classList.remove('active')};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('pointerleave',off)}
primary.onclick=()=>{if(state==='title')start(0);else if(state==='paused'){state='play';overlay.classList.add('hidden')}else if(state==='complete'){levelIndex<LEVELS.length-1?start(levelIndex+1):showLog()}};function showLog(){state='log';title.textContent='The Catch Log';copy.innerHTML=LEVELS.map((l,i)=>`${i<save.unlocked?'CAUGHT':'LOCKED'} - ${l.fish} ${save.times[i]?`- ${fmt(save.times[i])}`:''}`).join('<br>');primary.textContent='PLAY AGAIN';primary.onclick=()=>location.reload()}
document.querySelector('#sound').onclick=e=>{sound=!sound;e.target.textContent=`SOUND: ${sound?'ON':'OFF'}`};document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='play')pause()});requestAnimationFrame(loop);
