import {LEVELS,TILE} from './levels.js';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
const overlay=document.querySelector('#overlay'),title=document.querySelector('#overlay-title'),copy=document.querySelector('#overlay-copy'),primary=document.querySelector('#primary');
const keys=new Set(),pressed=new Set(); let state='title',levelIndex=0,level,player,camera=0,elapsed=0,deaths=0,pearls=0,shake=0,last=0,sound=true;
const save=JSON.parse(localStorage.getItem('reelbound-save')||'{"unlocked":1,"times":{}}');
class AudioFX{constructor(){this.ctx=null} tone(f,d=.08,v=.05,type='square'){if(!sound)return;this.ctx??=new AudioContext;const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,this.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,this.ctx.currentTime+d);o.connect(g).connect(this.ctx.destination);o.start();o.stop(this.ctx.currentTime+d)}}const fx=new AudioFX;
function resetLevel(i=levelIndex){levelIndex=i;level=LEVELS[i];player={x:level.start[0]*TILE,y:level.start[1]*TILE,w:22,h:28,vx:0,vy:0,ground:false,coyote:0,jumpBuffer:0,dashes:1,dashing:0,hook:null,face:1,inv:0};camera=0;elapsed=0;deaths=0;pearls=0;level._pearls=level.pearls.map((p,j)=>({x:p[0]*TILE+12,y:p[1]*TILE+12,taken:false,id:j}));level._enemies=level.enemies.map((p,j)=>({x:p[0]*TILE,y:p[1]*TILE,w:25,h:22,vx:j%2?55:-55,alive:true}));}
function start(i=0){resetLevel(i);state='play';overlay.classList.add('hidden');fx.tone(330,.12)}
function rects(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function solids(){return level.platforms.map(p=>({x:p[0]*TILE,y:p[1]*TILE,w:p[2]*TILE,h:p[3]*TILE}))}
function die(){if(player.inv>0)return;deaths++;shake=10;fx.tone(90,.3,.08,'sawtooth');Object.assign(player,{x:level.start[0]*TILE,y:level.start[1]*TILE,vx:0,vy:0,hook:null,inv:1})}
function moveAxis(axis,amount){player[axis]+=amount;for(const r of solids())if(rects(player,r)){if(axis==='x'){player.x=amount>0?r.x-player.w:r.x+r.w;player.vx=0}else{player.y=amount>0?r.y-player.h:r.y+r.h;player.vy=0;if(amount>0){player.ground=true;player.dashes=1}}}}
function nearestHook(){let best=null,dist=230;for(const h of level.hooks){const x=h[0]*TILE+16,y=h[1]*TILE+16,d=Math.hypot(x-(player.x+11),y-(player.y+8));if(d<dist&&y<player.y+80){best={x,y};dist=d}}return best}
function update(dt){if(state!=='play')return;elapsed+=dt;player.inv=Math.max(0,player.inv-dt);player.coyote=player.ground?.1:Math.max(0,player.coyote-dt);player.jumpBuffer=Math.max(0,player.jumpBuffer-dt);if(pressed.has('Space')||pressed.has('ArrowUp')||pressed.has('KeyZ'))player.jumpBuffer=.12;
 const dir=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0);if(dir)player.face=dir;
 if((pressed.has('KeyE')||pressed.has('KeyX'))&&!player.hook){player.hook=nearestHook();if(player.hook)fx.tone(520)}else if((pressed.has('KeyE')||pressed.has('KeyX'))&&player.hook)player.hook=null;
 if((pressed.has('ShiftLeft')||pressed.has('ShiftRight')||pressed.has('KeyC'))&&player.dashes&&!player.dashing){player.dashes--;player.dashing=.16;player.vx=player.face*520;player.vy=0;fx.tone(180,.14)}
 if(player.jumpBuffer&&player.coyote){player.vy=-410;player.jumpBuffer=0;player.coyote=0;player.ground=false;fx.tone(420)}
 const accel=level.ice?700:1500,drag=level.ice?.94:.78;player.vx=player.dashing?player.vx:(player.vx+dir*accel*dt)*Math.pow(drag,dt*10);player.vx=Math.max(-260,Math.min(260,player.vx));player.vy+=980*dt;player.ground=false;
 if(player.hook){const dx=player.hook.x-(player.x+11),dy=player.hook.y-(player.y+8),d=Math.hypot(dx,dy);player.vx+=dx/d*620*dt;player.vy+=dy/d*620*dt;if(d>225)player.hook=null;if(pressed.has('Space')){player.hook=null;player.vy=-380;player.vx+=player.face*80;fx.tone(620)}}
 player.dashing=Math.max(0,player.dashing-dt);if(level.wind)player.vx+=level.wind*dt;moveAxis('x',player.vx*dt);moveAxis('y',player.vy*dt);
 for(const h of level.hazards){if(rects(player,{x:h[0]*TILE,y:h[1]*TILE,w:h[2]*TILE,h:h[3]*TILE}))die()}if(player.y>570)die();
 for(const e of level._enemies){if(!e.alive)continue;e.x+=e.vx*dt;const foot={x:e.x,y:e.y+e.h+2,w:e.w,h:3};if(!solids().some(r=>rects(foot,r)))e.vx*=-1;if(rects(player,e)){if(player.vy>100||player.dashing){e.alive=false;player.vy=-220;fx.tone(120,.08)}else die()}}
 for(const p of level._pearls)if(!p.taken&&Math.hypot(player.x-p.x,player.y-p.y)<28){p.taken=true;pearls++;fx.tone(780,.12)}
 const goal={x:level.goal[0]*TILE,y:level.goal[1]*TILE,w:34,h:56};if(rects(player,goal))complete();camera+=(Math.max(0,player.x-330)-camera)*Math.min(1,dt*5);pressed.clear();}
function complete(){state='complete';const score=Math.max(0,10000-Math.floor(elapsed*70)-deaths*500+pearls*400),rank=score>8000?'S':score>6500?'A':score>4800?'B':'C';save.unlocked=Math.max(save.unlocked,levelIndex+2);save.times[levelIndex]=Math.min(save.times[levelIndex]||9999,elapsed);localStorage.setItem('reelbound-save',JSON.stringify(save));title.textContent=`${level.fish} caught!`;copy.innerHTML=`Stage ${levelIndex+1} clear · ${elapsed.toFixed(1)}s · ${pearls}/${level.pearls.length} pearls · ${deaths} falls<br><strong>RANK ${rank} · ${score} PTS</strong>`;primary.textContent=levelIndex===4?'VIEW CATCH LOG':'NEXT TIDE';overlay.classList.remove('hidden');fx.tone(660,.35,.06,'triangle')}
function px(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x-camera),Math.round(y),w,h)}
function drawPlayer(){const x=player.x,y=player.y,bob=player.ground&&Math.abs(player.vx)>20?Math.sin(elapsed*18)*2:0;if(player.inv&&Math.floor(player.inv*10)%2)return;if(player.hook){ctx.strokeStyle='#f4e1b8';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x+11-camera,y+8);ctx.quadraticCurveTo((x+player.hook.x)/2-camera,y+70,player.hook.x-camera,player.hook.y);ctx.stroke()}px(x+5,y+5+bob,14,12,'#efb34d');px(x+2,y+2+bob,19,6,'#ffd45b');px(x+7,y+11+bob,11,7,'#bd6843');px(x+4,y+17+bob,16,9,'#1f918d');px(x+2+(player.face<0?0:13),y+18+bob,6,4,'#f0c08a');px(x+4,y+26+bob,6,3,'#382f3c');px(x+14,y+26+bob,6,3,'#382f3c')}
function draw(){const g=ctx.createLinearGradient(0,0,0,540);g.addColorStop(0,level?.sky[0]||'#102d43');g.addColorStop(1,level?.sky[1]||'#da7656');ctx.fillStyle=g;ctx.fillRect(0,0,960,540);if(!level)return;
 const sx=(Math.random()-.5)*shake,sy=(Math.random()-.5)*shake;ctx.save();ctx.translate(sx,sy);shake*=.82;for(let i=0;i<12;i++){const x=((i*173-camera*.15)%1200+1200)%1200;px(x+camera,100+i%4*34,90,8,'#ffffff12')}
 px(camera,480,960,60,level.water);for(let i=0;i<32;i++)px(camera+i*34+(elapsed*18)%34,480+Math.sin(i+elapsed*2)*4,18,3,'#b9f0df');
 for(const p of level.platforms){const [x,y,w,h]=p;px(x*TILE,y*TILE,w*TILE,h*TILE,'#183c48');px(x*TILE,y*TILE,w*TILE,6,level.ice?'#b8eef0':'#4e9b72');for(let i=0;i<w;i+=2)px((x+i)*TILE,y*TILE+12,18,5,'#102d38')}
 for(const h of level.hazards)for(let i=0;i<h[2];i++){const x=(h[0]+i)*TILE,y=h[1]*TILE;px(x,y+18,32,14,'#0a405b');px(x+4,y+5,6,18,'#dbf1df');px(x+16,y,7,23,'#dbf1df')}
 for(const h of level.hooks){const x=h[0]*TILE+16,y=h[1]*TILE+16;px(x-4,y-4,8,8,'#ffbd47');px(x-2,y+4,4,7,'#fff1cf')}
 for(const p of level._pearls)if(!p.taken){px(p.x-5,p.y-5,10,10,'#fff4d7');px(p.x-2,p.y-7,4,3,'#82e5d5')}
 for(const e of level._enemies)if(e.alive){px(e.x,e.y+7,25,15,'#e65e48');px(e.x+4,e.y+2,5,7,'#f2b950');px(e.x+16,e.y+2,5,7,'#f2b950');px(e.x+(e.vx>0?18:4),e.y+9,3,3,'#071726')}
 const gx=level.goal[0]*TILE,gy=level.goal[1]*TILE;px(gx+14,gy,4,58,'#e4c287');px(gx+18,gy+8,28,18,'#ef6a4c');px(gx+25,gy+13,10,5,'#fff1cf');drawPlayer();ctx.restore();
 ctx.fillStyle='#071726cc';ctx.fillRect(16,16,330,53);ctx.fillStyle='#fff1cf';ctx.font='bold 14px DM Mono';ctx.fillText(`${levelIndex+1}/5  ${level.name.toUpperCase()}`,28,38);ctx.fillStyle='#7fded2';ctx.font='11px DM Mono';ctx.fillText(`${elapsed.toFixed(1)}s  ·  PEARLS ${pearls}/${level.pearls.length}  ·  FALLS ${deaths}`,28,57);}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}
addEventListener('keydown',e=>{if(!keys.has(e.code))pressed.add(e.code);keys.add(e.code);if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'&&state==='play'){state='paused';title.textContent='Lines slackened';copy.textContent='The tide will wait for you.';primary.textContent='RESUME';overlay.classList.remove('hidden')}});addEventListener('keyup',e=>keys.delete(e.code));
primary.onclick=()=>{if(state==='title')start(0);else if(state==='paused'){state='play';overlay.classList.add('hidden')}else if(state==='complete'){if(levelIndex<4)start(levelIndex+1);else showLog()}};
function showLog(){state='log';title.textContent='The Catch Log';copy.innerHTML=LEVELS.map((l,i)=>`${i<save.unlocked?'◆':'◇'} ${l.fish} ${save.times[i]?`— ${save.times[i].toFixed(1)}s`:''}`).join('<br>');primary.textContent='PLAY AGAIN';primary.onclick=()=>{primary.onclick=null;location.reload()}}
document.querySelector('#sound').onclick=e=>{sound=!sound;e.target.textContent=`SOUND: ${sound?'ON':'OFF'}`};requestAnimationFrame(loop);
